### PR TITLE
Fix defaultprevented for IE

### PR DESCRIPTION
**Pull request by joscha**
Using `.preventDefault()` on a CustomEvent in IE causes problems, see here: http://stackoverflow.com/questions/23349191

This PR adds a fix for this.

### CODE REVIEW

**Comment by joscha** [comment]
@krambuhl is this something you'd consider merging, or is there anything missing?

**Comment by joscha** [comment]
@krambuhl any chance to get this into master and a new version? Please?

**Comment by krambuhl** [comment]
@joscha thanks for your contribution of tested code!  sorry that I overlooked this.  I'll merge and publish a new minor version to npm tonight.

**Comment by joscha** [comment]
Awesome, that would be great! If you could add a comment here once the new version is out, that would be perfect!

**Comment by krambuhl** [comment]
It's actually already up!

**Comment by joscha** [comment]
O yay!! Thank you!

**Pull request merged**
